"""Concat 12 JSX files → guild-bundle.jsx (single Babel parse for prod cold-load).

Usage:
    python bundle.py            # writes guild-bundle.jsx in this folder
    python bundle.py --watch    # rebundle on file change (requires `watchfiles`)

Order matches guild.html script tags. Setiap file dibungkus IIFE supaya scope
nggak bocor antar-modul (semua API publik tetap diekspos via `Object.assign(window, {...})`
di akhir tiap file, jadi bundling aman).
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

HERE = Path(__file__).parent

# Urutan harus match guild.html.
ORDER = [
    "tweaks-panel.jsx",
    "guild-data.jsx",
    "guild-state.jsx",
    "guild-api.jsx",
    "guild-sprites.jsx",
    "guild-furniture.jsx",
    "guild-pets.jsx",
    "guild-interactions.jsx",
    "guild-scene.jsx",
    "guild-panels.jsx",
    "guild-app.jsx",
]

OUTPUT = HERE / "guild-bundle.jsx"

HEADER = """/* GUILD BUNDLE — auto-generated by bundle.py
   Concat order match guild.html. Edit each source file, not this bundle. */
"""

FOOTER = """
/* === BOOTSTRAP === */
const _root = ReactDOM.createRoot(document.getElementById("root"));
_root.render(<GuildApp />);
"""


def build() -> None:
    parts = [HEADER]
    for name in ORDER:
        path = HERE / name
        if not path.exists():
            print(f"[bundle] WARN: {name} tidak ada — skip", file=sys.stderr)
            continue
        body = path.read_text(encoding="utf-8")
        parts.append(f"\n/* ── {name} ── */\n")
        parts.append(body)
        if not body.endswith("\n"):
            parts.append("\n")
    parts.append(FOOTER)
    OUTPUT.write_text("".join(parts), encoding="utf-8")
    print(f"[bundle] wrote {OUTPUT.name} ({OUTPUT.stat().st_size:,} bytes, "
          f"{len(ORDER)} sources)")


def watch() -> None:
    try:
        from watchfiles import watch as wf_watch
    except ImportError:
        print("[bundle] --watch needs `pip install watchfiles`", file=sys.stderr)
        sys.exit(1)
    build()
    print("[bundle] watching for changes...")
    for changes in wf_watch(*[HERE / n for n in ORDER]):
        time.sleep(0.05)  # debounce burst writes
        build()


if __name__ == "__main__":
    if "--watch" in sys.argv[1:]:
        watch()
    else:
        build()
